Stack Trace Fallback Test: Tests correct behaviour of fallback advice
====================================================================================================


Uncaught exception foo-err:
	at void foo() in (functions.hh:8)
	at void foobar() in (functions.hh:10)
	at void bar() in (main.cc:6)
	at void barfoo() in (main.cc:6)

